TP1_PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import home.urls as home
import app_stats.urls as app_stats
import add_friend.urls as add_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(home,namespace='home')),
    url(r'^stats/', include(app_stats,namespace='app_stats')),
    url(r'^friend/', include(add_friend,namespace='add_friend')),
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True), name='index')
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend, name='add_friend'),
]

app_stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

home/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

add_friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	name = models.CharField(max_length = 27)
	url = models.URLField()
	date = models.DateTimeField(auto_now_add=True)

app_profile/models.py
from django.db import models

# Create your models here.

app_stats/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'This field is required',
        'invalid': 'Please fill in your friend\'s herokuapp link',
    }
    name_attrs = {
        'class': 'form-control',
        'placeholder':'What is your friend\'s name?'
    }

    url_attrs = {
        'class': 'form-control',
        'placeholder':'What is your friend\'s herokuapp link?'
    }


    name = forms.CharField(label='Name', required=True, max_length=27, empty_value='Anonymous', 
        widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='URL', required=True, empty_value='Anonymous',
        widget=forms.URLInput(attrs=url_attrs))
    

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

# Create your views here.
response = {}
def index(request):
	html = 'add_friend/add_friend.html'
	response['friend_form'] = Friend_Form
	friend = Friend.objects.all()
	response['friend'] = friend
	return render(request,html,response)
def add_friend(request):
	form = Friend_Form(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
		response['url'] = request.POST['url'] if request.POST['url'] != "" else "Anonymous"
		friend = Friend(name=form.cleaned_data['name'], url=form.cleaned_data['url'])
		friend.save()
	else:
		response['form'] = form
	html ='add_friend/add_friend.html'
	friend = Friend.objects.all()
	response['friend'] = friend
	return render(request,html,response)

app_profile/views.py
from django.shortcuts import render

# Create your views here.

app_stats/views.py
from django.shortcuts import render

def index(request):
    response = {}
    response["friends"] = 120;
    response["feed"] = 23;
    return render(request, 'stats.html', response)

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    response = {}
    return render(request, 'home.html', response)

add_friend/templates/add_friend/add_friend.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Friends</title>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
	
</head>
<body>
<section class="media container">
	<img class="title" src="{% static 'image/maintitle.png' %}" alt="Generic placeholder image" style="width:450px;height:200px;">
</section>

<hr/>
<section name="input-friend" id="input-friend">
    <div class="container">
        <form id="form" method="POST" action="{% url 'add_friend:add_friend' %}">
            <h2>Connect with Your Friend</h2>
            {% csrf_token %}
            {{ friend_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Add Friend">
        </form>
    </div>
</section>

<section name="friend" id="friend">
   	<div class="container">
   	<h2 class="friend-title">Friends</h2>
  	<table class="table">
        <thead>
            <th>Name</th>
            <th>URL</th>
            <th>Date</th>
        </thead>
        <tbody>
            
            {% for i in friend %}
            <tr class="success">
                <td> {{i.name}} </td>
                <td><a href="{{ i.url }}"> {{i.url}} </a></td>
                <td> {{i.date}} </td>
            </tr>             
            {% endfor %}
        </tbody>
    </table>
	</div>
</section>

<!-- Print errors if any -->
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <!-- List all previous status -->
    <div class="container stasuses">
        {% for i in status reversed %}
            <div class="flex-item">
                <h5> {{ i.user.name }} </h5>
                {{ i.friend }} <br/>
                <sub> {{ i.date }} </sub>
            </div>
        {% endfor %}
    </div>

</body>
</html>

app_stats/templates/stats.html
{% extends "base.html" %}
{% block content %}

<div style="margin-left: 50px; margin-right : 50px; background-color: rgba(255,255,255,0.5); height: 100% ">
    <h1 style="text-align: center"> Stats </h1>  
    <h2> Friend : {{friends}} </h2> 
    <h2> Feed : {{feed}} </h2> 
</div>
{% endblock %}

home/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="center_screen">
    <h1> Home </h1>    
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Title</title>
</head>
<style>
	body {
		margin : 0;
		background-color: #cccccc
	}

	.topnav {
		overflow: hidden;
		background-color: #474747;
		box-shadow: 0px 0px 0px red inset;
	}

	.topnav a {
		display: block;
		float: left;
		color: white;
		text-align: center;
		font-size: 20px;
		padding: 10px 15px;
		text-decoration: none;
		border-left: 1px #686868 solid;
		border-right: 1px #686868 solid;
		transition : box-shadow 0.2s;
	}

	.topnav a:hover {
		box-shadow: 0px -4px 0px red inset;		
	}

	.topnav a.first-item {
		border-left: none;
	}

	.topnav a.last-item {
		border-right: 2px solid #686868;
	}

</style>
<body>
	<div class="container">
		<div class="topnav">
			<a class="first-item" href="/home/"> Home </a>
			<a href="#profile"> Profile </a>
			<a href="#friend"> Friend </a>
			<a href="#status"> Status </a>
			<a class="last-item" href="/stats/"> Stats </a>	
		</div>			
	</div>
	{% block content %}
	{% endblock %}	
</body>

</html>